// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF7E5LqqU4o_r556OFpgLPAiFjOKj7Acc',
    appId: '1:973315752201:web:f9ecdbc1ff1cddbd9193d8',
    messagingSenderId: '973315752201',
    projectId: 'flutter-test-efa60',
    authDomain: 'flutter-test-efa60.firebaseapp.com',
    storageBucket: 'flutter-test-efa60.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLwnTerRSHHp1qm2N1sE8xUAcIQMtlEmE',
    appId: '1:973315752201:android:ff232fe4c4b6d5d79193d8',
    messagingSenderId: '973315752201',
    projectId: 'flutter-test-efa60',
    storageBucket: 'flutter-test-efa60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Y8pEPzVXDPjJqJVvavqBnJuN3vf9rOE',
    appId: '1:973315752201:ios:5075c81a82f191e29193d8',
    messagingSenderId: '973315752201',
    projectId: 'flutter-test-efa60',
    storageBucket: 'flutter-test-efa60.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7Y8pEPzVXDPjJqJVvavqBnJuN3vf9rOE',
    appId: '1:973315752201:ios:5075c81a82f191e29193d8',
    messagingSenderId: '973315752201',
    projectId: 'flutter-test-efa60',
    storageBucket: 'flutter-test-efa60.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF7E5LqqU4o_r556OFpgLPAiFjOKj7Acc',
    appId: '1:973315752201:web:0ce9a4b04678f7c09193d8',
    messagingSenderId: '973315752201',
    projectId: 'flutter-test-efa60',
    authDomain: 'flutter-test-efa60.firebaseapp.com',
    storageBucket: 'flutter-test-efa60.firebasestorage.app',
  );
}
